ENV = 'stg'
TARGET_DATABASE = "my_company_data"
TARGET_SCHEMA = "stg_data_metrics_layer"
PROJECT_PATH = "/usr/local/airflow/dags/wbr/metrics_dbt/scripts/"
MODELS_LIST = ['acquisition', 'conversion', 'monetisation', 'retention', 'supply', 'anaplan_budget_data_daily']
BKFILL_MODELS = ['acquisition', 'conversion', 'monetisation', 'retention', 'supply', 'anaplan']
MART_TO_MODEL_MAP = {'acquisition':'acquisition_mart', 'conversion':'conversion_mart', 'monetisation':'monetisation_mart', 'retention':'retention_mart', 'supply':'supply_mart', 'anaplan':'anaplan_budget_data_daily_mart'}
BKFILL_MODELS_ALL = ['acquisition_mart', 'anaplan_budget_mart', 'conversion_mart', 'monetisation_mart', 'retention_mart', 'supply_mart', 'wbr_breakout_report', 'wbr_overview_report']
CONN_ID = 'dbt_trino_dev'
MKT_TBL = 'marketing_refresh_daily'
MKT_TBL_EVNG = 'marketing_refresh_daily_evening'
MKT_TBL_TASK_ID = 'marketing_mart.marketing_mart_end'
CUST_TBL = 'customer_model'
USER_TBL = 'user_growth_refactor_iceberg_daily'
FM_TBL = 'orderlines_fm_update'
DATA_TAG = ["tag:datamarts"]
OVR_VIEW = ["tag:overview"]
DATA_MAINTENANCE = ["tag:data_maintenance"]
BREAKOUT_REPORT = ["tag:breakout_report"]
WEBHOOK_CHANNEL = '#data-mece-alerts'
WEBHOOK_SMM_NAME = 'bi_mece_dq_check_fail_webhook_url'
